DATA:
  DATASET: tiger-beetle
  IMG_SIZE: 192
  NUM_WORKERS: 32
MODEL:
  TYPE: swinv2
  NAME: swinv2_base_window12
  PRETRAINED: /local/scratch/stevens.994/hierarchical-vision/pretrained-checkpoints/groovy-grape-192-epoch89.pth
  DROP_PATH_RATE: 0.2
  SWINV2:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 12
    PRETRAINED_WINDOW_SIZES: [ 12, 12, 12, 6 ]
TRAIN:
  GLOBAL_BATCH_SIZE: 16

  EPOCHS: 30
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.1

SWEEP:
  PARAMETERS:
    BASE_LR: 
      max: 1.0e-2
      min: 1.0e-8
    WARMUP_LR:
      max: 1.0e-3
      min: 1.0e-9
    MIN_LR:
      max: 1.0e-3
      min: 1.0e-9
    BATCH_SIZE: 
      values: [ 4, 8, 16, 32, 64, 128 ]
    EPOCHS:
      values: [ 5, 10, 15, 30, 60 ]

EXPERIMENT:
  NAME: groovy-grape
