DATA:
  DATASET: nabird
  IMG_SIZE: 192
  NUM_WORKERS: 32
MODEL:
  TYPE: swinv2
  NAME: swinv2_base_window12
  DROP_PATH_RATE: 0.0
  SWINV2:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 12
TRAIN:
  GLOBAL_BATCH_SIZE: 1024

  EPOCHS: 50
  WARMUP_EPOCHS: 2
  WEIGHT_DECAY: 0.0

  WARMUP_LR: 1e-9
  BASE_LR: 1e-6
  MIN_LR: 1e-6

EXPERIMENT:
  NAME: fuzzy-fig-1e-6-no-reg
  WANDB_ID: 1zg01e6nr
