DATA:
  DATASET: nabird
  IMG_SIZE: 192
  NUM_WORKERS: 32
MODEL:
  TYPE: swinv2
  NAME: swinv2_base_window12
  DROP_PATH_RATE: 0.0
  SWINV2:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 12
TRAIN:
  GLOBAL_BATCH_SIZE: 1024

  EPOCHS: 50
  WARMUP_EPOCHS: 2
  WEIGHT_DECAY: 0.0

  WARMUP_LR: 3e-8
  BASE_LR: 3e-5
  MIN_LR: 3e-5

EXPERIMENT:
  NAME: fuzzy-fig-3e-5-no-reg
  WANDB_ID: 3zg03e5nr
